version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: fakestore-mysql-db
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - my-network

networks:
  my-network: